Revert signature change in BDRU.registerWithGeneratedName
This change broke binary compatibility as evidenced by running
the greenhouse test suite and finding that Spring Integration's
AbstractConsumerEndpointParser.parseInternal fails with
NoSuchMethodError when trying to invoke.

git-svn-id: https://src.springframework.org/svn/spring-framework/trunk@3969 50f2f4bb-b051-0410-bef5-90022cba6387